# Generated by Django 2.0 on 2019-02-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='client_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
